const POST_TYPE_STANDARD = 0;
const POST_TYPE_POLL = 1;
const POST_TYPE_LINK = 2;
const NO_POLL_OPTION_UUID = "00000000-0000-0000-0000-000000000000";

const POST_VERB_POLL = "poll";

// TODO
// Changed temporarily, until logic improvement on getting the feeds is implemented.
//const MAX_FEED_FETCH_LIMIT = 10;
//const MAX_FEED_FETCH_LIMIT_DOMAIN = 20;
const MAX_FEED_FETCH_LIMIT = 100;
const MAX_FEED_FETCH_LIMIT_DOMAIN = 100;

const REDIS_TTL = 86400;
const BLOCK_DOMAIN_KEY = "BLOCK_DOMAIN_";
const BLOCK_FEED_KEY = "BLOCK_FEED_";
const BLOCK_POST_ANONYMOUS = "BLOCK_POST_ANONYMOUS_";
const API_PREFIX_V1 = "/api/v1";
const GETSTREAM_RANKING_METHOD = "betterscore";

module.exports = {
  POST_TYPE_STANDARD,
  POST_TYPE_POLL,
  POST_VERB_POLL,
  MAX_FEED_FETCH_LIMIT,
  REDIS_TTL,
  NO_POLL_OPTION_UUID,
  BLOCK_DOMAIN_KEY,
  MAX_FEED_FETCH_LIMIT_DOMAIN,
  BLOCK_FEED_KEY,
  BLOCK_POST_ANONYMOUS,
  API_PREFIX_V1,
  GETSTREAM_RANKING_METHOD,
};
