const ACTIVITY_THRESHOLD = {
  MAIN_FEED_FOLLOWING: process.env.THRESHOLD_MAIN_FEED_FOLLOWING || 0.0002,
  MAIN_FEED_F2: process.env.THRESHOLD_MAIN_FEED_F2 || 0.0002,
  MAIN_FEED_BROAD: process.env.THRESHOLD_MAIN_FEED_BROAD || 0.0002,
  TOPIC_FEED: process.env.THRESHOLD_TOPIC_FEED || 0.0002,
  MAIN_FEED: process.env.THRESHOLD_MAIN_FEED || 0.0002
};

module.exports = {
  ACTIVITY_THRESHOLD
};
