let BetterSocialEmojiList = []

function pushToEmojiList(name, emoji) {
    BetterSocialEmojiList.push({
        name: name,
        emoji: emoji
    })
}

pushToEmojiList("Pumpkin", "🎃")
pushToEmojiList("Balloon", "🎈")
pushToEmojiList("Teddy", "🧸")
pushToEmojiList("Joker", "🃏")
pushToEmojiList("Puppy", "🐶")
pushToEmojiList("Fox", "🦊")
pushToEmojiList("Cat", "🐱")
pushToEmojiList("Lion", "🦁")
pushToEmojiList("Tiger", "🐯")
pushToEmojiList("Horse", "🐴")
pushToEmojiList("Unicorn", "🦄")
pushToEmojiList("Zebra", "🦓")
pushToEmojiList("Deer", "🦌")
pushToEmojiList("Bison", "🦬")
pushToEmojiList("Cow", "🐮")
pushToEmojiList("Sheep", "🐑")
pushToEmojiList("Goat", "🐐")
pushToEmojiList("Camel", "🐪")
pushToEmojiList("Llama", "🦙")
pushToEmojiList("Girrafe", "🦒")
pushToEmojiList("Elephant", "🐘")
pushToEmojiList("Mammoth", "🦣")
pushToEmojiList("Rhino", "🦏")
pushToEmojiList("Mouse", "🐭")
pushToEmojiList("Hamster", "🐹")
pushToEmojiList("Rabbit", "🐰")
pushToEmojiList("Chipmunk", "🐿")
pushToEmojiList("Hedgehog", "🦔")
pushToEmojiList("Bear", "🐻")
pushToEmojiList("Polar Bear", "🐻‍❄️")
pushToEmojiList("Koala", "🐨")
pushToEmojiList("Panda", "🐼")
pushToEmojiList("Sloth", "🦥")
pushToEmojiList("Kangaroo", "🦘")
pushToEmojiList("Chicken", "🐔")
pushToEmojiList("Bird", "🐦")
pushToEmojiList("Penguin", "🐧")
pushToEmojiList("Dove", "🕊")
pushToEmojiList("Eagle", "🦅")
pushToEmojiList("Duck", "🦆")
pushToEmojiList("Swan", "🦢")
pushToEmojiList("Owl", "🦉")
pushToEmojiList("Dodo", "🦤")
pushToEmojiList("Flamingo", "🦩")
pushToEmojiList("Peacock", "🦚")
pushToEmojiList("Parrot", "🦜")
pushToEmojiList("Frog", "🐸")
pushToEmojiList("Crocodile", "🐊")
pushToEmojiList("Turtle", "🐢")
pushToEmojiList("Lizard", "🦎")
pushToEmojiList("Dragon", "🐉")
pushToEmojiList("Dino", "🦕")
pushToEmojiList("T-Rex", "🦖")
pushToEmojiList("Whale", "🐳")
pushToEmojiList("Dolphin", "🐬")
pushToEmojiList("Seal", "🦭")
pushToEmojiList("Fish", "🐟")
pushToEmojiList("Blowfish", "🐡")
pushToEmojiList("Shark", "🦈")
pushToEmojiList("Octopus", "🐙")
pushToEmojiList("Shell", "🐚")
pushToEmojiList("Snail", "🐌")
pushToEmojiList("Butterfly", "🦋")
pushToEmojiList("Catterpillar", "🐛")
pushToEmojiList("Bee", "🐝")
pushToEmojiList("Beetle", "🪲")
pushToEmojiList("Flower", "🌸")
pushToEmojiList("Ghost", "👻")
pushToEmojiList("Martian", "👽")
pushToEmojiList("Robot", "🤖")
pushToEmojiList("Moon", "🌙")
pushToEmojiList("Sun", "🌞")
pushToEmojiList("Snowman", "⛄")





module.exports = BetterSocialEmojiList